### ISSUE TITLE
Consider using queries from `nvim-treesitter-textobjects`

### ISSUE THREAD

**Issue by igorlfs** [SleepySwords/change-function.nvim#1]
Hey! Great job with the plugin! I was just thinking about hacking a similar plugin myself :)

I was wondering if you considered using queries from [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects). It bundles a bunch of queries, for many languages, but most notably, it provides a `@parameter` that could be helpful (among other queries). 

Besides, it's a nice reference for the swap itself, since it also provides this functionality (for the current reference only).

**Comment by SleepySwords** [comment]
Ah, I didn't consider using queries from nvim-treesitter-textobjects, that's so smart. I will try and look into being able to use those queries.

We might need to extend the textobjects queries to either detect and handle or exclude something like `self` within Rust or python as they mess up the swapping of function arguments.
