### ISSUE TITLE
Feature: Splitting "Change the function" and function discovery as separate steps

### ISSUE THREAD

**Issue by ColinKennedy** [SleepySwords/change-function.nvim#6]
I tried out writing a scm query for Python and testing if it properly find + replace the function arguments and its function references in a file. Running `:lua require("change-function").change_function()` worked to replace the function + its references once or twice and then hasn't again and I'm unsure why. I confirmed that the LSP sees other references by calling `:norm gr` to create a quickfix window with all function references so it definitely should be swapping but change_function is not swapping as expected.

Part of what made it hard to work with the plugin is that I don't know in advance what this plugin sees and which function calls, if any, are about to be edited.

It'd be significantly better user experience IMO if the user could see each place that will be replaced and, if needed, append / modify that list of function references. To get that to work, we could reuse Neovim's quickfix/location list.

I could envision a refactor of this Neovim plugin that works like this:

- Hover your cursor over the function that you want to replace
- Call `:norm gr` (LSP show references in the quickfix window)
- Maybe the user wants to exclude one or two of the results for some reason so they edit the quickfix list
- Or append to the quickfix window because LSP didn't find every reference the first time
    - Existing plugins that let you edit the quickfix window would integrate super well here. Example: [vim-qfedit](https://github.com/itchyny/vim-qfedit)
- With the cursor still positioned over the function, the user calls `:lua require("change-function").open_window()` and reorders the function arguments as usual
- User closes the floating window

- User then calls `:cdo require("change-function").change_function()` so the quickfix window can run on each found result.

Now there's no ambiguity about what is about to be replaced. The user knows exactly which function argument(s) are changing and each place where it will be changed. And if their LSP isn't 100% perfect at finding all of the references, the user can still adjust the references before continuing. And the setup uses Neovim built-ins so it integrates well with other tools.

What do you think of this?

**Comment by SleepySwords** [comment]
> worked to replace the function + its references once or twice and then hasn't again and I'm unsure why

That is odd, it might be that Treesitter cannot match all the results from the LSP, so the entire swap fails. I will try to add better error handling, that better notifies the user what is happening with Treesitter. Is there anything in `:messages` or whatever notify plugin you use?

>It'd be significantly better user experience IMO if the user could see each place that will be replaced and, if needed, append / modify that list of function references. To get that to work, we could reuse Neovim's quickfix/location list.
> 
> I could envision a refactor of this Neovim plugin that works like this:

I like this idea! I think it works really well with people's existing workflows, where they would already use their quickfix list to do refactors. I still think that there should be an alternative way that a user can change their function automatically without using a quickfix list.

I could see having two commands, one would fetch and change based on what is in the quickfix list (we could consolidate the final two commands into one by looking at the quickfix list directly) and the other uses LSP references (which is what it is doing currently).

Also, I was wondering, would you prefer if Treesitter failed to match any queries that
a) The entire replace fails, so nothing is replaced?
b) change_function will try to swap arguments with the ones it can swap, but doesn't do anything with the ones it can't.

**Comment by ColinKennedy** [comment]
> Is there anything in :messages or whatever notify plugin you use?

I don't think there was but I can try again later today and see. 

> I still think that there should be an alternative way that a user can change their function automatically without using a quickfix list.

> I could see having two different functions, one would fetch and change based on what is in the quickfix list (we could consolidate the final two commands into one by looking at the quickfix list directly) and the other uses LSP references (which is what it is doing currently).

This is exactly what I was thinking too :)! We could have it both ways. If people want a "one call" solution like the plugin currently works because they know that the LSP will do exactly what they want, change-function can continue to provide a function to do that. I they want confirmation / customization, other functions can exist for that. A (very simplified) API could be something like ...

- `change_function_from_gui` = The current change_function(), basically
- `save_changes` + `change_function_from_saved` = a quickfix + "do the replacement" it command


```lua
local M = {}
local _RECENT_CHANGES = nil

local function do_replacement() ... end

local function do_replacements(changes, references, strict)
    if not strict then
        for _, reference in ipairs(references) do
            -- Try to replace per element, skip each replacement if it cannot be replaced
            do_replacement(changes, reference)
        end

        return
    end

    local invalids = {}

    for _, reference in ipairs(references) do
        if not is_valid(changes, reference) then
            table.insert(invalids, reference)

            break
        end
    end

    if not okay then
        vim.notify(
             string.format(
                 'Cannot replace "%s" references with "%s" changes.', 
                 vim.inspect(references),
                 vim.inspect(changes)
            )
        )

        return
    end

    for _, reference in ipairs(references) do
        -- Do all replacements. Technically the replacements are still per element 
        -- but because we validated each replacement beforehand, 
        -- we know that each replacement will work
        --
        do_replacement(changes, reference)
    end
end


function M.change_function_from_gui(strict)
    local references = M.get_references()
    local changes = M.open_window()

    do_replacements(changes, references, strict)
end


function M.open_window()
    -- Do "open the window and get the users changes logic
    return ... -- A description of what the user wants to swap around
end

function M.save_changes()
    _RECENT_CHANGES = M.open_window()
end

function M.change_function_from_saved(strict)
    local references = get_references_from_quickfix()

    do_replacements(_RECENT_CHANGES, references, strict)
end
```

> Also, I was wondering, would you prefer if Treesitter failed to match for a particular function that
> a) The entire swap fails, so nothing is swap?
> b) change_function will try to swap arguments with the ones it can swap, but doesn't do anything with the ones it can't.

If I had to choose one I think I'd choose b and errors like how in Neovim you can do `:cdo s/foo/bar` and it will error on all files that didn't match or do `:cdo s/foo/bar/e` to silence the errors. However I think a + b are also possible in one API. In the pseudo-code above, `strict`, when `true`, is used to check the swaps in advance and fails early. When `strict` is `false` it just tries what it can.

**Comment by SleepySwords** [comment]
> I don't think there was but I can try again later today and see.

If you want to try again, I pushed some changes that hopefully have more noticeable and more helpful errors :)

> This is exactly what I was thinking too :)! We could have it both ways. If people want a "one call" solution like the plugin currently works because they know that the LSP will do exactly what they want, change-function can continue to provide a function to do that. I they want confirmation / customization, other functions can exist for that. A (very simplified) API could be something like ...

Ah nice, thanks for the pseudocode! I was playing around with the quickfix functions and found out that you can get the currently selected entry from the quickfix list. So there are two possible flows.

1. Put references in the quickfix list -> Add/modify -> Call function (uses the selected entry in the quickfix list for the source of arguments in the UI) -> Confirm -> The changes are applied to the quickfix list entries.
2. Put references in the quickfix list -> Add/modify -> Move back to the window -> Call function (uses the function in the cursor the source of arguments in the UI) -> Confirm -> The changes are applied to the quickfix list entries.

I think this will be an option within the setup, I'm leaning toward having the 2nd option be the default (and doing the 1st if the cursor is within the qf list).

What do you think about this?

> If I had to choose one I think I'd choose b and errors like how in Neovim you can do :cdo s/foo/bar and it will error on all files that didn't match or do :cdo s/foo/bar/e to silence the errors. However I think a + b are also possible in one API. In the pseudo-code above, strict, when true, is used to check the swaps in advance and fails early. When strict is false it just tries what it can.

Right makes sense, yea I think that's a good enough reason to have strict be false as the default.
